### ISSUE TITLE
您好，后台编译过程中报错请问这是什么原因？

### ISSUE THREAD

**Issue by artuoliya** [rawchen/Blog#3]
[ERROR] Tests run: 4, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 8.95 s <<< FAILURE! - in com.rawchen.BlogApiApplicationTests
[ERROR] test02  Time elapsed: 0.014 s  <<< ERROR!
java.lang.IllegalStateException: Expected method not found: java.lang.NoSuchMethodException: java.lang.String.valueOf(java.lang.String)
	at com.rawchen.BlogApiApplicationTests.test02(BlogApiApplicationTests.java:26)

2022-01-25 10:35:34.971  INFO 3316 --- [extShutdownHook] org.quartz.core.QuartzScheduler          : Scheduler quartzScheduler_$_NON_CLUSTERED paused.
2022-01-25 10:35:34.982  INFO 3316 --- [extShutdownHook] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'
2022-01-25 10:35:34.984  INFO 3316 --- [extShutdownHook] o.s.s.quartz.SchedulerFactoryBean        : Shutting down Quartz Scheduler
2022-01-25 10:35:34.985  INFO 3316 --- [extShutdownHook] org.quartz.core.QuartzScheduler          : Scheduler quartzScheduler_$_NON_CLUSTERED shutting down.
2022-01-25 10:35:34.986  INFO 3316 --- [extShutdownHook] org.quartz.core.QuartzScheduler          : Scheduler quartzScheduler_$_NON_CLUSTERED paused.
2022-01-25 10:35:34.987  INFO 3316 --- [extShutdownHook] org.quartz.core.QuartzScheduler          : Scheduler quartzScheduler_$_NON_CLUSTERED shutdown complete.
2022-01-25 10:35:35.142  INFO 3316 --- [extShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2022-01-25 10:35:35.170  INFO 3316 --- [extShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   BlogApiApplicationTests.test02:26 ? IllegalState Expected method not found: ja...
[INFO] 
[ERROR] Tests run: 4, Failures: 0, Errors: 1, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  16.522 s
[INFO] Finished at: 2022-01-25T10:35:35+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project blog-api: There are test failures.
[ERROR] 
[ERROR] Please refer to /root/Blog/blog-api/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by rawchen** [comment]
搜maven打包跳过测试


 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月25日 10:37:00
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [rawchen/Blog] 您好，后台编译过程中报错请问这是什么原因？ (Issue #3)




 
[ERROR] Tests run: 4, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 8.95 s <<< FAILURE! - in com.rawchen.BlogApiApplicationTests
 [ERROR] test02  Time elapsed: 0.014 s  <<< ERROR!
 java.lang.IllegalStateException: Expected method not found: java.lang.NoSuchMethodException: java.lang.String.valueOf(java.lang.String)
 at com.rawchen.BlogApiApplicationTests.test02(BlogApiApplicationTests.java:26)
 
2022-01-25 10:35:34.971  INFO 3316 --- [extShutdownHook] org.quartz.core.QuartzScheduler          : Scheduler quartzScheduler_$NON_CLUSTERED paused.
 2022-01-25 10:35:34.982  INFO 3316 --- [extShutdownHook] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'
 2022-01-25 10:35:34.984  INFO 3316 --- [extShutdownHook] o.s.s.quartz.SchedulerFactoryBean        : Shutting down Quartz Scheduler
 2022-01-25 10:35:34.985  INFO 3316 --- [extShutdownHook] org.quartz.core.QuartzScheduler          : Scheduler quartzScheduler$NON_CLUSTERED shutting down.
 2022-01-25 10:35:34.986  INFO 3316 --- [extShutdownHook] org.quartz.core.QuartzScheduler          : Scheduler quartzScheduler$NON_CLUSTERED paused.
 2022-01-25 10:35:34.987  INFO 3316 --- [extShutdownHook] org.quartz.core.QuartzScheduler          : Scheduler quartzScheduler$_NON_CLUSTERED shutdown complete.
 2022-01-25 10:35:35.142  INFO 3316 --- [extShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
 2022-01-25 10:35:35.170  INFO 3316 --- [extShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
 [INFO]
 [INFO] Results:
 [INFO]
 [ERROR] Errors:
 [ERROR]   BlogApiApplicationTests.test02:26 ? IllegalState Expected method not found: ja...
 [INFO]
 [ERROR] Tests run: 4, Failures: 0, Errors: 1, Skipped: 0
 [INFO]
 [INFO] ------------------------------------------------------------------------
 [INFO] BUILD FAILURE
 [INFO] ------------------------------------------------------------------------
 [INFO] Total time:  16.522 s
 [INFO] Finished at: 2022-01-25T10:35:35+08:00
 [INFO] ------------------------------------------------------------------------
 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project blog-api: There are test failures.
 [ERROR]
 [ERROR] Please refer to /root/Blog/blog-api/target/surefire-reports for the individual test results.
 [ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
 [ERROR] -&gt; [Help 1]
 [ERROR]
 [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
 [ERROR] Re-run Maven using the -X switch to enable full debug logging.
 [ERROR]
 [ERROR] For more information about the errors and possible solutions, please read the following articles:
 [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by artuoliya** [comment]
> 搜maven打包跳过测试
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年1月25日 10:37:00 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [rawchen/Blog] 您好，后台编译过程中报错请问这是什么原因？ (Issue #3) [ERROR] Tests run: 4, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 8.95 s <<< FAILURE! - in com.rawchen.BlogApiApplicationTests [ERROR] test02 Time elapsed: 0.014 s <<< ERROR! java.lang.IllegalStateException: Expected method not found: java.lang.NoSuchMethodException: java.lang.String.valueOf(java.lang.String) at com.rawchen.BlogApiApplicationTests.test02(BlogApiApplicationTests.java:26) 2022-01-25 10:35:34.971 INFO 3316 --- [extShutdownHook] org.quartz.core.QuartzScheduler : Scheduler quartzScheduler_$NON_CLUSTERED paused. 2022-01-25 10:35:34.982 INFO 3316 --- [extShutdownHook] o.s.s.concurrent.ThreadPoolTaskExecutor : Shutting down ExecutorService 'applicationTaskExecutor' 2022-01-25 10:35:34.984 INFO 3316 --- [extShutdownHook] o.s.s.quartz.SchedulerFactoryBean : Shutting down Quartz Scheduler 2022-01-25 10:35:34.985 INFO 3316 --- [extShutdownHook] org.quartz.core.QuartzScheduler : Scheduler quartzScheduler$NON_CLUSTERED shutting down. 2022-01-25 10:35:34.986 INFO 3316 --- [extShutdownHook] org.quartz.core.QuartzScheduler : Scheduler quartzScheduler$NON_CLUSTERED paused. 2022-01-25 10:35:34.987 INFO 3316 --- [extShutdownHook] org.quartz.core.QuartzScheduler : Scheduler quartzScheduler$_NON_CLUSTERED shutdown complete. 2022-01-25 10:35:35.142 INFO 3316 --- [extShutdownHook] com.zaxxer.hikari.HikariDataSource : HikariPool-1 - Shutdown initiated... 2022-01-25 10:35:35.170 INFO 3316 --- [extShutdownHook] com.zaxxer.hikari.HikariDataSource : HikariPool-1 - Shutdown completed. [INFO] [INFO] Results: [INFO] [ERROR] Errors: [ERROR] BlogApiApplicationTests.test02:26 ? IllegalState Expected method not found: ja... [INFO] [ERROR] Tests run: 4, Failures: 0, Errors: 1, Skipped: 0 [INFO] [INFO] ------------------------------------------------------------------------ [INFO] BUILD FAILURE [INFO] ------------------------------------------------------------------------ [INFO] Total time: 16.522 s [INFO] Finished at: 2022-01-25T10:35:35+08:00 [INFO] ------------------------------------------------------------------------ [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project blog-api: There are test failures. [ERROR] [ERROR] Please refer to /root/Blog/blog-api/target/surefire-reports for the individual test results. [ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream. [ERROR] -&gt; [Help 1] [ERROR] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch. [ERROR] Re-run Maven using the -X switch to enable full debug logging. [ERROR] [ERROR] For more information about the errors and possible solutions, please read the following articles: [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;



> 搜maven打包跳过测试
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年1月25日 10:37:00 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [rawchen/Blog] 您好，后台编译过程中报错请问这是什么原因？ (Issue #3) [ERROR] Tests run: 4, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 8.95 s <<< FAILURE! - in com.rawchen.BlogApiApplicationTests [ERROR] test02 Time elapsed: 0.014 s <<< ERROR! java.lang.IllegalStateException: Expected method not found: java.lang.NoSuchMethodException: java.lang.String.valueOf(java.lang.String) at com.rawchen.BlogApiApplicationTests.test02(BlogApiApplicationTests.java:26) 2022-01-25 10:35:34.971 INFO 3316 --- [extShutdownHook] org.quartz.core.QuartzScheduler : Scheduler quartzScheduler_$NON_CLUSTERED paused. 2022-01-25 10:35:34.982 INFO 3316 --- [extShutdownHook] o.s.s.concurrent.ThreadPoolTaskExecutor : Shutting down ExecutorService 'applicationTaskExecutor' 2022-01-25 10:35:34.984 INFO 3316 --- [extShutdownHook] o.s.s.quartz.SchedulerFactoryBean : Shutting down Quartz Scheduler 2022-01-25 10:35:34.985 INFO 3316 --- [extShutdownHook] org.quartz.core.QuartzScheduler : Scheduler quartzScheduler$NON_CLUSTERED shutting down. 2022-01-25 10:35:34.986 INFO 3316 --- [extShutdownHook] org.quartz.core.QuartzScheduler : Scheduler quartzScheduler$NON_CLUSTERED paused. 2022-01-25 10:35:34.987 INFO 3316 --- [extShutdownHook] org.quartz.core.QuartzScheduler : Scheduler quartzScheduler$_NON_CLUSTERED shutdown complete. 2022-01-25 10:35:35.142 INFO 3316 --- [extShutdownHook] com.zaxxer.hikari.HikariDataSource : HikariPool-1 - Shutdown initiated... 2022-01-25 10:35:35.170 INFO 3316 --- [extShutdownHook] com.zaxxer.hikari.HikariDataSource : HikariPool-1 - Shutdown completed. [INFO] [INFO] Results: [INFO] [ERROR] Errors: [ERROR] BlogApiApplicationTests.test02:26 ? IllegalState Expected method not found: ja... [INFO] [ERROR] Tests run: 4, Failures: 0, Errors: 1, Skipped: 0 [INFO] [INFO] ------------------------------------------------------------------------ [INFO] BUILD FAILURE [INFO] ------------------------------------------------------------------------ [INFO] Total time: 16.522 s [INFO] Finished at: 2022-01-25T10:35:35+08:00 [INFO] ------------------------------------------------------------------------ [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project blog-api: There are test failures. [ERROR] [ERROR] Please refer to /root/Blog/blog-api/target/surefire-reports for the individual test results. [ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream. [ERROR] -&gt; [Help 1] [ERROR] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch. [ERROR] Re-run Maven using the -X switch to enable full debug logging. [ERROR] [ERROR] For more information about the errors and possible solutions, please read the following articles: [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

好的谢谢。
